#!/usr/bin/env bash

if [ $1 = "build-all" ]; then
  for img in base shell golang
  do
    docker build ./images/${img} -t ddev-${img}
  done
  docker image prune -f
else
  docker run --rm -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v ~/.ssh/id_rsa.pub:/home/ddev/.ssh/id_rsa.pub \
    -v ~/.ssh/id_rsa:/home/ddev/.ssh/id_rsa \
    ddev-$1:latest
fi
